### ISSUE TITLE
Thoughts on handling networking config?

### ISSUE THREAD

**Issue by Schachte** [larstobi/terraform-provider-multipass#25]
Currently, I've been working on static IPv4 assignments for my VMs, which is necessary for local IaC development when IP addresses are expected to be deterministic as I bring up/tear down machines.

Unfortunately, there isn't great interop with ARM & Multipass (ie. M1 mac), but I've gotten something jank kind of working per these docs. https://multipass.run/docs/configure-static-ips

Weirdly though, I cannot have this entire setup work with cloud-init alone. It seems like I have to manually apply a new netplan file and apply it as two separate steps. Only then do I see an IP assignment and MAC addresses matching what I expect. 

```
multipass exec -n test12 -- sudo bash -c 'cat << EOF > /etc/netplan/10-custom.yaml                                                                      
network:
    version: 2
    ethernets:
        extra0:
            dhcp4: no
            match:
                macaddress: "52:54:00:4b:ab:dd"
            addresses: [192.168.64.78/24]
EOF'
```

In order for this to work, I create my VMs with some special arguments:

```
multipass launch --name my-vm-test --network name=en0,mode=manual,mac="52:54:00:4b:ab:dd" --cloud-init cloud-init.yaml
```

As you can see, I supply the `en0` interface, which is listed as an available bridge via `multipass networks` along with a static MAC address that is later linked via the netplan yaml above. 

It would be nice to be able to support passing in the `network_name` and `mac_address` as parameters in the Terraform provider to handle this during initialization so I can keep it all self-contained in Terraform. Does this seem reasonable? I'd be happy to work on this if so. Open to discussing this as I'm new to Multipass and find the networking to be both poorly documented and convoluted.
